---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: lemon-mango
# description will be included in the image's metadata
description: Bazzite with mangowm/noctalia

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite
image-version: stable # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - foot
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
        - plasma-desktop 

  - type: dnf
    repos:
      copr:
        - kaleedtc/mangowm
    install:
      packages:
        - mangowm
  
  - type: dnf
    repos:
      copr:
        - lionheartp/Hyprland
    install:
      packages:
        - nwg-look
        - noctalia
        - noctalia-greeter

  - type: dnf
    repos:
      copr:
        - boobaa/zen-browser
    install:
      packages:
        - zen-browser
        
  - type: dnf
    install:
      packages:
        - adw-gtk3-theme
        - qt5ct
        - qt6ct
        - nautilus
        - xdg-desktop-portal-wlr
        - sqlite-devel
        - xdg-utils
        - gcc
        - papirus-icon-theme
      exclude:
        - plasma-desktop 

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
